language: php
sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

addons:
  postgresql: "9.6"

services:
  - postgresql

matrix:
  fast_finish: true
  include:
    # - php: 5.4
    # - php: 5.5
    - php: 5.6
    # - php: 7.0
    # - php: 7.1
    # - php: 7.2
    # - php: nightly

before_install:
  - if [ -f /home/travis/.phpenv/versions/$TRAVIS_PHP_VERSION/etc/conf.d/xdebug.ini ]; then phpenv config-rm xdebug.ini; fi
  - for f in $(find . -path './vendor' -prune -o -name \*.php -print) ; do php -l $f ; done # Do this first!
  - composer self-update # May help using cache for php packages.
  - ls /home/travis/.phpenv/versions/5.6/etc/conf.d
  - phpenv config-add ~travis.php.ini # name choosen for it to be executed after travis.ini
  - ls /home/travis/.phpenv/versions/5.6/etc/conf.d
  # Shows the (alphabetical) order used for execution, last executed overrides the parameters
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql --dbname=postgres --command='\l'
  - psql --dbname=travis_ci_test --command='\d'
  - psql --host=/var/run/postgresql --dbname=travis_ci_test --command='\d'
  - psql --username=postgres --host=/var/run/postgresql --dbname=travis_ci_test --command='\d'
  - psql --help

install:
  - composer validate
  - if [[ $TRAVIS_PHP_VERSION = '7.1' ]]; then composer require --dev friendsofphp/php-cs-fixer; fi
  - composer install --no-scripts --no-progress --no-suggest
  - cp config/parameters.yml.travis config/parameters.yml
  - composer up --no-progress --no-suggest --optimize-autoloader --apcu-autoloader
  - composer show
  - chmod u+x ./bin/console
  - ./bin/console
  - ./bin/console dbal:list-databases
  # - ./bin/console doctrine:schema:update ############################### Does it still rely on ORM for schema?

before_script:

script:
  - ./bin/console dbal:schema:update
  - ./bin/console dbal:schema:getMigrateToSql
  # this checks that the source code follows the Symfony Code Syntax rules
  - if [[ $TRAVIS_PHP_VERSION = '7.1' ]]; then ./vendor/bin/php-cs-fixer fix --stop-on-violation --diff --dry-run -vvv --using-cache=no; fi
  # this checks that the YAML config files contain no syntax errors
  - ./bin/console lint:yaml config
  # - ./bin/console lint:yaml @CodeExplorerBundle
  # this checks that the Twig template files contain no syntax errors
  # - ./bin/console lint:twig templates @CodeExplorerBundle
  - ./bin/console lint:twig templates
  # this checks that the XLIFF translations contain no syntax errors
  - ./bin/console lint:xliff templates
  # this checks that the application doesn't use dependencies with known security vulnerabilities
  - ./vendor/bin/simple-phpunit
  - ./vendor/bin/simple-phpunit tests
  - ./bin/console security:check --end-point=http://security.sensiolabs.org/check_lock
  - for f in $(find ./vendor -name \*.php) ; do php -l $f > /dev/null ; done # Should be the last line of install but sometimes long to execute and little can be done for errors found.

# inspirated from 
  # symfony/symfony-demo
  # TODO: https://github.com/doctrine/dbal/blob/v2.5.13/.travis.yml
